services:
  db:
    container_name: postgres_panini
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: panini
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  db:
